baseURL= "/"
publishDir = "docs"
languageCode= "en"
title= "ECF Network"
paginate = 5
copyright = "All rights reserved - 2019"
theme = "hero"
disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = [ "\\.foo$", "\\.boo$" ]

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[blackfriday]
  angledQuotes = true
  hrefTargetBlank = true

[params]
  description = "Welcome to my website"
  metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  cover = ""
  author = "YOUR_NAME"
  authorlocation = "Earth, Milky Way Galaxy"
  authorwebsite = ""
  authorbio= ""
  logo = ""
  hjsStyle = "default"
  paginatedsections = ["posts"]
  google_analytics_id=""

# [[menu.main]]
# name = "Work"
# url = "/work/"
# weight = 1
# 
[[menu.main]]
identifier = "develop"
name = "Develop"
url = "/develop/"
weight = 2
# 
# [[menu.main]]
# identifier = "platforms"
# name = "Platforms"
# url = "/platforms/"
# weight = 3

# [[menu.main]]
# parent = "platforms"
# name = "Ethereum"
# url = ""
# weight = 1
# 
# [[menu.main]]
# parent = "platforms"
# name = "EOS"
# url = ""
# weight = 1

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4